feedback/urls.py
#from django.contrib import admin
from . import views
from django.urls import path, include

app_name = 'feedback'

urlpatterns = [
    path('', views.feedback, name='feedback'),
    path('add-feedback', views.add_feedback, name='add_feedback'),
    path('delete-feedback/<int:id>', views.delete_feedback, name='delete_feedback'),
    path('getData/', views.getData, name='getData'),
    path('parseData/<str:query>', views.parseData, name='parseData'),
    path('getDataAll/', views.getDataAll, name='getDataAll'),
    path('parseDataAll/', views.parseDataAll, name='parseDataAll'),
    path('message/', views.message, name='message')
]

tk/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('donation/', include('donation.urls')),
    path('covcase/', include('covcase.urls')),
    path('feedback/', include('feedback.urls')),
    path('FAQ/', include('FAQapp.urls')),
    path('artikel/', include('artikel.urls')),
    path('users/', include('users.urls')),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path('', views.index, name='index'),
    path('signup/', views.signup_page, name='signup'),
    path('login/', views.login_page, name='login'),
    path('logout/', views.logout_acc, name='logout'),
]

feedback/models.py
from django.db import models

# Create your models here.

class Feedback(models.Model):
	name = models.CharField(max_length=200)
	email = models.CharField(max_length=200)
	message = models.TextField()

	def __str__(self):
		return "{} - {} - {}".format(self.name, self.email, self.message)

class Message(models.Model):
    message_content = models.CharField(max_length=300)
    message_author_username = models.CharField(max_length=300,default="")
    no = models.CharField(max_length=10,default="")
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "{} - {}".format(self.message_author_username, self.message_content)

feedback/forms.py
from django.shortcuts import render, redirect
from django import forms
from .models import Feedback, Message
#from . import forms
from django.forms import ModelForm
# from . import models

class CreateFeedbackForm(forms.ModelForm):
	class Meta:
		model = Feedback 
		fields = [
			"message",
		]

class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = [
            'message_content',
        ]

        widgets = {
        	'message_content': forms.TextInput(
        		attrs = {
					'class': 'form-control'
        		}
        	)
        }

feedback/views.py
from django.shortcuts import render, redirect
from .forms import CreateFeedbackForm, MessageForm
from .models import Feedback, Message
from . import forms
from users.models import Profile
from django.contrib.auth.models import User
from django.http import JsonResponse, HttpResponse
import json
import requests
from django.core import serializers

# Create your views here.
def feedback(request):

    feedback = Feedback.objects.all()
    response = {
    	'title' : 'Feedback',
        'feedback': feedback,
        'messages': Message.objects.all(),
        'message_form': MessageForm()
    }

    return render(request, 'feedback_page.html', response)

def add_feedback(request):
    response = {
        'title' : 'Add Feedback',
        'feedback_form': CreateFeedbackForm()
    }

    if request.method == "POST":
        feedback_form = CreateFeedbackForm(request.POST)
        if feedback_form.is_valid():
            feedback = feedback_form.save(commit=False)
            user = request.user
            user_profile = Profile.objects.get(user=user)
            name = user_profile.nama
            email = user.email
            feedback.name = name
            feedback.email = email
            feedback.save()
            return redirect('feedback:feedback')
    return render(request, 'add_feedback_page.html', response)

def delete_feedback(request, id):
    feedback = Feedback.objects.get(id=id)
    feedback.delete()
    return redirect('feedback:feedback')

def getData(request):
    q = request.GET['q']
    url = 'http://fightcov-19-2.herokuapp.com/feedback/parseData/' + q

    response = requests.get(url)
    response_json = response.json()
    return JsonResponse(response_json, safe=False)

def parseData(request, query):
    queryResult = []

    for feedback in Feedback.objects.all():
        if(query.lower() in feedback.name.lower()):
            queryResult.append(feedback)

    feedback_list = serializers.serialize('json', queryResult)
    return HttpResponse(feedback_list, content_type="application/json")

def getDataAll(request):
    url = 'http://fightcov-19-2.herokuapp.com/feedback/parseDataAll/'

    response = requests.get(url)
    response_json = response.json()
    return JsonResponse(response_json, safe=False)
    
def parseDataAll(request):
    feedback = Feedback.objects.all()

    feedback_list = serializers.serialize('json', feedback)
    return HttpResponse(feedback_list, content_type="application/json")

def message(request):
    if request.method == "POST":
        data = json.loads(request.body)
        form = MessageForm({'message_content' : data['message_content']})

        if form.is_valid():
            banyak = Message.objects.all().count()
            author = User.objects.get(username=request.user)
            item = form.save(commit=False)
            item.message_author_username = author.username
            item.no = str(banyak+1)
            item.save()
            print(Message.objects.last().message_content)
            return JsonResponse({
                'message_content' : Message.objects.last().message_content,
                'author' : Message.objects.last().message_author_username,
                'no' : str(banyak+1),
                'created_at' : Message.objects.last().created_at,
            })
        print(form.errors)

feedback/templates/add_feedback_page.html
{% extends 'base_layout.html' %} 
{% load static %}

{% block meta %}
<link rel="stylesheet" href="{% static 'css/style_add_feedback.css' %}">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.js"></script>
{% endblock %}

{% block content %}

{% if user.is_authenticated %}
    <div class="course">
        <div style="display: flex; justify-content: left; padding-top: 1rem; padding-left: 1rem;"><button class="btn btn-add-feedback btn-unhovered" id="custom-button"><a href="{% url 'feedback:feedback' %}">See all the feedback!</a></button></div>

        <div style="text-align: right; justify-content: right; margin-right: 1rem; padding-top: -15rem; top: 2px;">
            <script>
            $(document).ready(function(){
                $("#button").click(function(){
                    alert("Please give the honest feedback so that our website will be better and more useful for everyone. Thank you and stay safe!");
                });
            });
            </script>
            <input type="button" style="background: #CA89FA; text-align: center; color: white; border-radius: 10px;width: 150px; height: 45px; border: 2px solid #CA89FA; align-items: center; margin-top: -40px;" id="button" value="! Reminder !">
        </div>

        <div class="wrap-course">
            <h1 style="color: #004850; font-size: 33px; font-family: Roboto;"><b>Form Feedback FightCov-19</b></h1>
            <div class="wrap">
                <form action="{% url 'feedback:add_feedback' %}" method="POST">
                    {% csrf_token %}
                    {% for field in feedback_form.visible_fields %}
                    <div class="form-group">
                        <div class="col-sm-6 offset-sm-3">
                            <h5>{{field.label_tag}} {{field}}</h5>
                        </div>
                    </div>
                    {% endfor %}
                    <div style="display: flex; justify-content: center; text-align: center"><button class="btn btn-add-feedback btn-unhovered" id="custom-button" type="submit">Submit</button></div>
                </form>
            </div>
        </div>
    </div>

{% else %}
<div class="not-authenticated"><body style="background-color: #D6F8FE">
    <b>You're not authenticated. <br/> Please <span style="color: red;">Log In</span> to write your feedback. <br/>
    If you don't have an account yet, click <span style="color: red;">Sign Up</span>.</b><br/>
    <div class="button-ls" style="margin-top: 1rem;">
        <button class="btn btn-add-feedback btn-unhovered" id="custom-button"><a href="{% url 'users:login' %}">Log In</a></button>&nbsp; &nbsp;
        <button class="btn btn-add-feedback btn-unhovered" id="custom-button"><a href="{% url 'users:signup' %}">Sign Up</a></button>
    </div>
</div>
{% endif %}

<script>
    $('.btn-add-feedback').mouseover(function() {
        $(this).removeClass('button-unhovered');
        $(this).addClass('button-hovered')
    });
    $('.btn-add-feedback').mouseleave(function() {
        $(this).removeClass('button-hovered');
        $(this).addClass('button-unhovered');
    });
</script>

{% endblock %}

feedback/templates/feedback_page.html
{% extends 'base_layout.html' %}
{% load static %}

{% block meta %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<script src="{% static 'js/search_bar_feedback.js' %}"></script>
<script src="{% static 'js/message_bar_feedback.js' %}"></script>
<link rel="stylesheet" href="{% static 'css/style_feedback.css' %}">
{% endblock meta %}

{% block content %}
<div class="feedback">
    <div class="wrap">
        {% if feedback.count %}
        <h1 style="text-align: center; font-size: 31px; color: #004850; font-family: Roboto;"><b>Thank you for visiting our website!</b></br><b>We really appreciate your feedback :)</b></h1>
        <button class="btn btn-feedback btn-unhovered" id="custom-button"><a href="{% url 'feedback:add_feedback' %}">Write your feedback!</a></button>

        <div class="form-group" style="padding-top: 1.5rem;">
            <div class="col-sm-6 offset-sm-3">
                <input id="search" class="form-control" type="text" placeholder="Search for your name here...">
            </div>
        </div>

        <div id="result">
        <div class="flex-wrap">
        {% for feedback_content in feedback %}
	        <div class="card">
	        	<div class="name">
	            	<h4 style="text-align: center;">{{ feedback_content.name }}</h4>
	        	</div>
	        	<div class="email">
	        		<h6 style="text-align: center;">{{ feedback_content.email }}</h6>
	        	</div>
	            <a href="{% url 'feedback:delete_feedback' id=feedback_content.id %}"><i class="fa fa-trash" aria-hidden="true"></i></a>
	            <div class="card-message">
	            	<h5 style="text-align: center; font-size: 15px;">{{ feedback_content.message }}</h5>
	            </div>
	        </div>

        {% endfor %}
    	</div>
    	</div>
        {% else %}

        <div class="else"><body style="background-color: #D6F8FE">
        	<div class="text">
        		<div class="text-1">
	            	<h4><b style="color: #202546; font-size: 27px;">We need your feedback :)</b></h4>
	            </div>
	            <div class="text-2">
	            	<button class="btn btn-feedback button-unhovered" id="custom-button"><a href="{% url 'feedback:add_feedback' %}" style="font-size: 16.5px;">Write here!</a></button>
	            </div>
	        </div>
        </div></body>

        {% endif %}

        <div class="message">
        	<h2 style="font-size: 30px; color: #004850; text-align: center;"><b>Put your message for our team:</b></h2>
            {% if user.is_authenticated %}
            <form action="" method="POST">
				{% csrf_token %}

                <div class="col-sm-6 offset-sm-3">
					{% for field in message_form %}
                    	{{field}}
                    {% endfor %}
                </div>

                <div style="margin: 15px;"></div>

                <button class="btn btn-feedback button-unhovered" id="custom_button" onclick="writeContent()">			Submit!		
                </button>

                <div style="margin: 15px;"></div>
            </form>

            {% else %}

            <div style="display: flex; justify-content: center;">
                <button class="btn btn-feedback button-unhovered" id="custom_button"><a href="{% url 'users:login' %}">Please Log In to write!</a></button>
            </div>
            {% endif %}

            {% if user.is_authenticated %}
            <div id="message_result">
            	<div style="display: flex; justify-content: center;">
                    <div class="message-wrapper" id="real_result">
                        {% for message in messages %}
                        <div class="message-item">
                            <div class="message-content">
                                {{message.no}}.&nbsp;{{message.message_content}}
                            </div>
                            <div class="message-author">
                                by {{message.message_author_username}}, <i>at {{message.created_at}}</i>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
            {% endif %}
        </div>
    </div>
</div>

<script>
    $('.btn-feedback').mouseover(function() {
        $(this).removeClass('button-unhovered');
        $(this).addClass('button-hovered')
    });
    $('.btn-feedback').mouseleave(function() {
        $(this).removeClass('button-hovered');
        $(this).addClass('button-unhovered');
    });

	$(function() {
		var len_fit_name = 19;

		$('.name h4').each(function(i, obj) {
			var name = $(this)
			
			var len_item_name = name.html().length;
			if(len_fit_name < len_item_name) {
	    		var size_now = parseInt(name.css("font-size"));
	    		var size_new = size_now * len_fit_name/len_item_name;
	    		name.css("font-size",size_new);
			}
		})

		var len_fit_email = 30;

		$('.email h6').each(function(i, obj) {
			var email = $(this)
			
			var len_item_email = email.html().length;
			if(len_fit_email < len_item_email) {
	    		var size_now = parseInt(email.css("font-size"));
	    		var size_new = size_now * len_fit_email/len_item_email;
	    		email.css("font-size",size_new);
			}
		})
    });
</script>

{% endblock %} 